bookkeeping_nc3_academy/bookkeeping_nc3_academy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# serving files in /media
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^certifications/', include('certifications.urls')),

    url(r'^', include('public.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookkeeping_nc3_academy/certifications/urls.py
from django.conf.urls import url

from . import views

app_name = 'certifications'
urlpatterns = [
    url(r'^topics/(?P<id>[0-9]+)/$', views.TopicViews.detail, name='topic_detail'),
    url(r'^topics/(?P<id>[0-9]+)/update/', views.TopicViews.update, name='topic_update'),
]

bookkeeping_nc3_academy/certifications/models.py
from django.db import models

# Create your models here.
class Certification(models.Model):
	"""docstring for Certification"""
	num_code = models.IntegerField(null=False)
	certification = models.CharField(max_length=50)
	alias = models.CharField(max_length=50, null=True)
	issuing_body = models.CharField(max_length=50, null=True)
	
	
class Topic(models.Model):
	"""docstring for Topic"""
	certification = models.ForeignKey(Certification, related_name='topics')
	order = models.IntegerField(null=False)
	topic = models.CharField(max_length=50)
	description = models.CharField(max_length=100, null=False)

bookkeeping_nc3_academy/courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
	"""docstring for Course"""
	code = models.CharField(max_length=10, null=True)
	course = models.CharField(max_length=50)
	course_image = models.ImageField(upload_to='courses/', null=True, blank=True)
	description = models.CharField(max_length=100)
	url = models.URLField()

bookkeeping_nc3_academy/certifications/forms.py
from django import forms

from .models import Certification, Topic


class TopicForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        model = Topic
        fields = '__all__'

bookkeeping_nc3_academy/certifications/views.py
from django.shortcuts import render, get_object_or_404
from django.forms import model_to_dict

from .models import Certification, Topic
from .forms import TopicForm

# Create your views here.
class TopicViews():
	"""docstring for TopicViews"""
	def detail(request, id):
		model = get_object_or_404(Topic, pk=id)
		
		form = TopicForm(instance=model, initial=model_to_dict(model))

		context = {
			'model': model,
			'form': form
		}

		return render(request, 'certifications/topics/detail.html', context)

	def update(request, id):
		if request.method == 'POST':
			model = get_object_or_404(Topic, pk=id)
			form = TopicForm(request.POST, instance=model)

			context = {
			'form' : form,
			'model': model,
			}

			fail = render(request, 'certifications/topics/detail.html', context)

			if form.has_changed():
				if form.is_valid():
					form.save()
				else:
					return fail

		return HttpResponseRedirect(reverse('public:index'))

bookkeeping_nc3_academy/courses/views.py
from django.shortcuts import render

# Create your views here.

bookkeeping_nc3_academy/certifications/templates/certifications/topics/detail.html
{% extends "base_project.html" %}

{% load static %}

{% block title %}Certification Topic - Detail{% endblock title %}

{% block nav %}
	{{ block.super }}    
{% endblock nav %}

{% block content %}


    <form id="id-form-update" enctype="multipart/form-data" action="{% url 'certifications:topic_update' model.id%}" method="post" class="form">
        {% csrf_token %}

        <div class="panel-group">
            <div class="panel panel-default">
                <a data-toggle="collapse" href="#id-div-model" aria-expanded="true">
                    <div class="panel-heading bg-inverse color-gray">
                        <h4 class="panel-title">
                            Topic
                        </h4>
                    </div>
                    
                </a>
            <div id="id-div-model" aria-expanded="true" class="collapse show" >
                <div class="panel-body">
                    <table class="table table-condensed table-bordered" id="id-table-contact">
                        <tbody>
                            {{ form.as_table }}
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>

        <!-- submit button -->
            <button form='id-form-update' class="btn btn-success btn-block action-save" type="submit" title="Update" id='id-bottom'>
                Save
            </button>
    </form>

{% endblock content %}

bookkeeping_nc3_academy/templates/base_project.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %} | Bookkeeping NC3 Academy</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.0.0-alpha.6-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">
    <style type="text/css">
        html, body {
            height: 100%;
            font-family: "Segoe UI";
        }
        .btn-page-top-bottom{
             position:fixed;
             bottom:0;
             right:0;
        }
        .color-black{
            color: black;
        }
        .color-white{
            color: #fff;
        }
        .color-black{
            color: #212121;
        }
        .color-gray{
            color: rgba(255, 255, 255, 0.5);
        }
        .icon-actions{
            font-size: 30px;
        }
        .icon-label{
            font-size: 20px;
        }
        .bg-black{
            background-color: #212121;
        }
        .bg-facebook-blue{
            background-color: #3B5998;
        }
        .bg-facebook-medium-blue{
            background-color: #6d84b4;
        }
        .bg-facebook-lighter-blue{
            background-color: #afbdd4;
        }
        .bg-facebook-lightest-blue{
            background-color: #d8dfea;
        }
        .color-facebook-lightest-blue{
            color: #d8dfea;
        }
        .btn-social {
          width: 3.25rem;
          height: 3.25rem;
          font-size: 1.25rem;
          line-height: 2rem; 
        }
    </style>
    {% block head %}{% endblock head %}
</head>
<body data-spy="scroll" data-target="#navbarNav">
    <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-facebook-blue" role="navigation">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#" style="color: #d8dfea;"><strong>BookkeepingNC3Academy</strong></a>
      <div class="collapse navbar-collapse scroll" id="navbarNav">
        <ul class="nav navbar-nav navbar-right" role="tablist" style="text-decoration: underline;">
                {% block nav %}

                {% endblock nav %}
        </ul>
      </div>
    </nav>




            {% block content %}
                <div class="content">
                    <p>Soon to rise...</p>
                </div>
            {% endblock content %}

    <div class="copyright py-4 text-center text-white bg-facebook-blue">
      <div class="container">
        <small>Copyright &copy; bookkeepingnc3academy.com 2017</small>
      </div>
    </div>

    <div id="id-bottom"></div>
    
    <div class="btn-page-top-bottom">
        <a href="#id-top"><i class="fa fa-arrow-up color-black"></i></a>
        <a href="#id-bottom"><i class="fa fa-arrow-down color-black"></i></a>
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/utils.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tether.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-4.0.0-alpha.6-dist/js/bootstrap.min.js' %}"></script>

    {% include 'includes/js/common.html' %}
    
    {% block script %}{% endblock script %}

</body>
</html>

bookkeeping_nc3_academy/templates/includes/js/common.html
    <script type="text/javascript">
        $(document).ready(function(){
            $('.action-delete').click(function(e){
                if (!confirm('Are you sure to delete this record?')) {
                    e.preventDefault()
                    return
                } else {
                }
            })

            $('.action-save').click(function(e){
                if (!confirm('Kindly make sure to review entries. Continue saving?')) {
                    e.preventDefault()
                    return
                } else {
                }
            })

            $('.action-detail').click(function(e){
                alias = $(this).data('action-alias')
                if (!confirm('View ' + alias + '\s detail?')) {
                    e.preventDefault()
                    return
                } else {
                }
            })
        })
    </script>